---
# Install MapR OpenTSDB

- name: Install mapr-opentsdb
  package: name=mapr-opentsdb state=present
  register: opentsdb_result

- name: Find OpenTSDB Path
  find: paths="/opt/mapr/opentsdb/" patterns="opentsdb*" file_type=directory
  register: opentsdb_path_result
  failed_when: opentsdb_path_result.matched != 1

- name: Set tsd.storage.hbase.data_table in opentsdb.conf
  lineinfile: dest={{ opentsdb_path_result.files[0].path }}/etc/opentsdb/opentsdb.conf regexp="^tsd\.storage\.hbase\.data_table" line="tsd.storage.hbase.data_table = /var/mapr/custom.tsdb/tsdb"
- name: Set tsd.storage.hbase.uid_table in opentsdb.conf
  lineinfile: dest={{ opentsdb_path_result.files[0].path }}/etc/opentsdb/opentsdb.conf regexp="^tsd\.storage\.hbase\.uid_table" line="tsd.storage.hbase.uid_table = /var/mapr/custom.tsdb/tsdb-uid"
- name: Set tsd.storage.hbase.meta_table in opentsdb.conf
  lineinfile: dest={{ opentsdb_path_result.files[0].path }}/etc/opentsdb/opentsdb.conf regexp="^tsd\.storage\.hbase\.meta_table" line="tsd.storage.hbase.meta_table = /var/mapr/custom.tsdb/tsdb-meta"

- name: Find Asyncbase Path
  find: paths="/opt/mapr/asynchbase/" patterns="asynchbase*" file_type=directory
  register: asynchbase_path_result
  failed_when: asynchbase_path_result.matched != 1
- name: Find Asynchbase Path JAR
  find: paths="{{ asynchbase_path_result.files[0].path }}" patterns="asynchbase*.jar" file_type=file
  register: asynchbase_jar_path_result
  failed_when: asynchbase_jar_path_result.matched == 0
- name: Link Asynchbase.jar to OpenTSDB
#  debug: msg="{{ item.path }}"
  file: src={{ item.path }} dest={{ opentsdb_path_result.files[0].path }}/share/opentsdb/lib/{{ item.path | basename }} state=link
  with_items: "{{ asynchbase_jar_path_result.files }}"
- name: Create custom OpenTSDB table structure
  shell: "{{ opentsdb_path_result.files[0].path }}/share/opentsdb/tools/create_table.sh"
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
    MONITORING_VOLUME_NAME: custom.tsdb
- name: Copy to /opt/mapr/conf/conf.d/warden.opentsdb.conf
  copy: remote_src=true src={{ opentsdb_path_result.files[0].path }}/etc/conf/warden.opentsdb.conf  dest=/opt/mapr/conf/conf.d/warden.opentsdb.conf mode=0644 owner={{ mapr_user }} group={{ mapr_user }}
- name: Create OpenTSDB Role
  file: dest=/opt/mapr/roles/opentsdb mode=0644 owner={{ mapr_user }} group={{ mapr_user }} state=touch
- name: Configure.sh -R
  shell: /opt/mapr/server/configure.sh -R
  when: opentsdb_result.changed
- name: Restart OpenTSDB
  shell: maprcli node services -name opentsdb -action restart -nodes {{ ansible_fqdn }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 10
  ignore_errors: yes
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: opentsdb_result.changed


