---
# Install MapR OpenTSDB

- name: Install mapr-opentsdb
  package: name=mapr-opentsdb state=present

# Bugfix create table
- name: Find OpenTSDB Path
  find: paths="/opt/mapr/opentsdb/" patterns="opentsdb*" file_type=directory
  register: opentsdb_path_result
  failed_when: opentsdb_path_result.matched != 1
- name: Find Asyncbase Path
  find: paths="/opt/mapr/asynchbase/" patterns="asynchbase*" file_type=directory
  register: asynchbase_path_result
  failed_when: asynchbase_path_result.matched != 1
- name: Find Asynchbase Path JAR
  find: paths="{{ asynchbase_path_result.files[0].path }}" patterns="asynchbase*.jar" file_type=file
  register: asynchbase_jar_path_result
  failed_when: asynchbase_jar_path_result.matched == 0
- name: Link Asynchbase.jar to OpenTSDB
#  debug: msg="{{ item.path }}"
  file: src={{ item.path }} dest={{ opentsdb_path_result.files[0].path }}/share/opentsdb/lib/{{ item.path | basename }} state=link
  with_items: "{{ asynchbase_jar_path_result.files }}"
- name: Create custom OpenTSDB table structure
  shell: "{{ opentsdb_path_result.files[0].path }}/share/opentsdb/tools/create_table.sh"
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
